### ISSUE TITLE
Scoreboard is transparent, and is in the top right of the screen

### ISSUE THREAD

**Issue by Gittified** [SuomiPelaajaa/esx_scoreboard#1]
Hey I've got this problem that my scoreboard is in the top right of the screen and that the background is transparent, however it doesn't look like the screenshots on the readme. Could anybody tell me what CSS is wrong? Thanks
![image](https://user-images.githubusercontent.com/28195796/54994054-9fd0f780-4fc3-11e9-99cc-2fa437fa08ec.png)

**Comment by Cactusje** [comment]
Also /scid doesn't work. I can only see Phone ping and name.

**Comment by SuomiPelaajaa** [comment]
yea we are releasing new version probably today

**Comment by nidelix** [comment]
This is not an issue. Try to change style.css color.
